# Model arguments
model_name_or_path: ai21labs/AI21-Jamba-1.5-Mini
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_mixer:
  HuggingFaceH4/deita-10k-v0-sft: 1.0
dataset_splits:
- train_sft
- test_sft
preprocessing_num_workers: 12

# SFT trainer config
bf16: true
dataset_kwargs:
  add_special_tokens: false # We already wrap them in the chat template
  append_concat_token: false # No need to add <eos> across samples
do_eval: false
eval_strategy: epoch
gradient_accumulation_steps: 1
hub_model_id: Jamba-1.5-Mini-Full-FT
hub_private_repo: true
hub_strategy: every_save
learning_rate: 1.0e-06
log_level: info
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 4096
max_steps: -1
num_train_epochs: 3
output_dir: Jamba-1.5-Mini-Full-FT
overwrite_output_dir: true
per_device_eval_batch_size: 2
per_device_train_batch_size: 2
push_to_hub: true
remove_unused_columns: true
#report_to:
#- tensorboard
#- wandb
save_strategy: "no"
seed: 42
warmup_ratio: 0.01
ddp_timeout: 3600
fsdp: "full_shard auto_wrap"
fsdp_transformer_layer_cls_to_wrap: "JambaAttentionDecoderLayer,JambaMambaDecoderLayer"
fsdp_config: "fsdp_config.json"